#!/bin/sh
set -e
if [ $GITHUB_REPOSITORY = 'DanySK/upgradle' ]
    then
    ./gradlew publishKotlinMavenPublicationToCentralS01Repository
    # Publish on GitHub. Fails due to overwritings, so it's ok to give up
    ./gradlew publishKotlinMavenPublicationToGithubRepository --continue || true
    ./gradlew githubRelease
fi
