_reference_jdk: &reference_jdk
  JDK="adopt@1.8"

language: minimal
os:
  - macos
  - windows
  - linux
env:
  global:
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
    - TERM="dumb"
  matrix:
    - *reference_jdk
    - JDK="adopt-openj9@1.8"
    - JDK="adopt@"
    - JDK="adopt-openj9"

stages:
  - base
  - test
  - deploy

jobs:
  exclude:
    - stage: test
      os: linux
      env: *reference_jdk
  include:
    - stage: base
      os: linux
      env: *reference_jdk
      after_success: bash <(curl -s https://codecov.io/bash)

before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk
install:
  - ./gradlew clean check jacocoTestReport
before_cache:
  - $GRAVIS/clean-gradle-cache
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
