if: branch = master OR tag ~= /\d+(\.\d+)*/

_reference_jdk: &reference_jdk
  JDK="adopt@1.8"

_reference_build: &reference_build
  os: linux
  env: *reference_jdk

language: minimal
os:
  - macos
  - windows
  - linux
env:
  global:
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
    - TERM="dumb"
  matrix:
    - *reference_jdk
    - JDK="adopt-openj9@1.8"
    - JDK="adopt@"
    - JDK="adopt-openj9"

stages:
  - base
  - test
  - deploy

jobs:
  exclude:
    - <<: *reference_build
      stage: test
  include:
    - <<: *reference_build
      stage: base
      after_success: bash <(curl -s https://codecov.io/bash)
    - <<: *reference_build
      stage: deploy
      script: travis_retry ./gradlew shadow dokka githubRelease publish

before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk
script:
  - travis_retry ./gradlew clean check jacocoTestReport
before_cache:
  - $GRAVIS/clean-gradle-cache
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
