if: type != push OR tag IS blank OR tag ~= /^\d+(\.\d+)*$/

_reference_jdk: &reference_jdk
  JDK="adopt@1.8"

_reference_build: &reference_build
  os: linux
  env: *reference_jdk

git:
  depth: false
  autocrlf: input

language: minimal
os:
  - macos
  - windows
  - linux
env:
  global:
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
    - TERM="dumb"
  matrix:
    - *reference_jdk
    - JDK="adopt-openj9@1.8"
    - JDK="adopt@"
    - JDK="adopt-openj9"

stages:
  - base
  - test
  - name: deploy
    if: type != pull_request AND repo = DanySK/upgradle AND branch = master

jobs:
  exclude:
    - <<: *reference_build
      stage: test
  include:
    - <<: *reference_build
      stage: base
      after_success: bash <(curl -s https://codecov.io/bash)
      script:
        - travis_retry ./gradlew clean check jacocoTestReport
    - <<: *reference_build
      stage: deploy
      install:
        - openssl aes-256-cbc -K $encrypted_f778b2e1574b_key -iv $encrypted_f778b2e1574b_iv -in secrets.asc.enc -out secrets.asc -d
        - export ORG_GRADLE_PROJECT_signingKey=$(cat secrets.asc)
        - rm secrets.asc
      script: travis_retry ./gradlew shadow dokka githubRelease publish

before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk
script:
  - travis_retry ./gradlew clean check
before_cache:
  - $GRAVIS/clean-gradle-cache
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
