name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * SUN'
    
jobs:
  Build:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
        jvm_version: [8, 11, 14]
    runs-on: ${{ matrix.os }}-latest
    env:
      CI: true
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
      MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      MAVEN_CENTRAL_USERNAME: danysk
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jvm_version }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - shell: bash 
        run: ./gradlew check --parallel
      - if: ${{ matrix.os == 'ubuntu' && matrix.jvm_version == 8 }}
        run: 
          ./gradlew publishMavenCentralPublicationToMavenRepository --parallel
